[pytest]
markers =
    api: Тесты API
    unit: Юнит-тесты
    tms_action: Тестирование действий администратора системы
    tester_action: Тестирование действий тестировщика
    end_to_end: Тесты проходящие по пользовательским сценариям